version: "3.8"

services:
  api:
    container_name: aegislenz-BE
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../model/best_model.pth:/app/ai/model/best_model.pth
      - ../model/label_encoder.pkl:/app/ai/model/label_encoder.pkl
    depends_on:
      - redis
      - mongodb
    environment:
      TZ: Asia/Seoul
    networks:
      - aegislenz-internal
    env_file:
      - .env

  redis:
    container_name: aegislenz-redis
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - aegislenz-internal

  mongodb:
    container_name: aegisLenz-mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - aegislenz-internal
    env_file:
      - .env

networks:
  aegislenz-internal:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
