name: CI/CD for FastAPI

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub 저장소에서 코드를 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: false

      # SSH 키 설정 (원격 서버 및 Private Repo 인증)
      - name: Setup SSH Keys for Private Repo and Server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/aegislenz
          chmod 600 ~/.ssh/aegislenz
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/aegislenz
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # 원격 서버로 SSH 접속 및 배포
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USER }}
          debug: true
          script_stop: true
          script: |
            cd AegisLenz/AegisLenz-BE
            git pull origin dev

            # 서브모듈 동기화 및 업데이트
            git submodule sync
            git submodule update --init --recursive
            git submodule update --remote

            # Docker 컨테이너 재배포
            docker-compose -p aegislenz down
            docker-compose -p aegislenz -f docker-compose.yml -f docker-compose.prod.yml up --build -d
