name: CI/CD for FastAPI

on:
  push:
    branches:
      - dev

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/aegislenz:latest
  COMPOSE_FILE: /home/jyjyjy25/AegisLenz/docker-compose-aegis.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub 저장소에서 코드를 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker 이미지 빌드 및 푸쉬
      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} --platform linux/amd64 .
          docker push ${{ env.DOCKER_IMAGE }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 서버에 SSH로 접속하여 환경설정 및 배포
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWD }}
          script_stop: true
          script: |
            echo "${{ secrets.ENV }}" > /home/jyjyjy25/AegisLenz/.env
            docker-compose -f ${{ env.COMPOSE_FILE }} -p aegislenz down || true
            docker pull ${{ env.DOCKER_IMAGE }}
            docker-compose -f ${{ env.COMPOSE_FILE }} -p aegislenz up -d
