name: CI/CD for FastAPI

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub 저장소에서 코드를 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          persist-credentials: false

      # 서버에 SSH로 접속하여 환경설정 및 배포
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWD }}
          script_stop: true
          script: |
            cd AegisLenz/AegisLenz-BE
            git pull origin dev

            git submodule sync
            git submodule update --init --recursive
            git submodule update --remote

            docker-compose -p aegislenz down
            docker-compose -p aegislenz up --build -d
